### ISSUE TITLE
三个问题

### ISSUE THREAD

**Issue by yqsy** [HitChainFoundation/hitchain#2]
1.  ipfs项目为MIT版权,你们把人家源码连同历史搞下来(为了增加项目commits),还把人家版权文件删掉,改成自己的GPL,构成侵权.

2. 买僵尸粉,300个星星一堆僵尸,把中国的陋习全带过来了,丢脸.

3. 你们的爬虫源码是实习生写的么,ip,mysql账号,密码,数据库都暴露了.赶紧把历史清空,以免被别人删库了.

conn = pymysql.connect(host="47.254.66.180",
                       port=3306,
                       user="root",
                       passwd="password",
                       db="ossean_coin_rank",
                       charset='utf8')

好心提醒,不用谢.

**Comment by yqsy** [comment]
你们是在做这个项目吗?

**Comment by HitChainFoundation** [comment]
yqsy您好，
我们计划的技术路线是基于ipfs开展，项目正式发布一定会继承license。之前发布的commits是对我们感兴趣的开发者在测试github仓库，不是正式项目代码。

另外，您是否对ipfs和git感兴趣呢？希望能跟您深入探讨，可以展开有价值的合作。

**Comment by yqsy** [comment]
我对ipfs 和filecoin的落地项目比较感性趣,如果你们的确真正在做这个事情,我会一起研究贡献微薄的力量.
